name       : go-task
version    : 3.24.0
release    : 1
homepage   : https://taskfile.dev/
source     :
    - https://github.com/go-task/task/archive/refs/tags/v3.24.0.tar.gz : e1ab3c92299ad5741b8b0e9dc18593db80efaca449b8ccc318a6ff1848b44338
license    : MIT
component  : programming.tools
networking : yes
summary    : A task runner / simpler Make alternative written in Go 
description: |
    A task runner / simpler Make alternative written in Go 
builddeps  :
    - golang
environment: |
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
    # Make sure the version ends up in the binary. go-releaser typically handles this but we're not using that
    sed -i "s|version = \"\"|version = \"v$version\"|g" internal/version/version.go
build      : |
    go build -v -o bin ./cmd/task
install    : |
    install -Dm00755 bin/task -t $installdir/usr/bin

    # symbolic link in case anyone is expecting this to be go-task instead
    ln -s task $installdir/usr/bin/go-task

    # Completions
    install -Dm00644 completion/bash/task.bash $installdir/usr/share/bash-completion/completions/task
    install -Dm00644 completion/zsh/_task $installdir/usr/share/zsh/site-functions/_task
    install -Dm00644 completion/fish/task.fish $installdir/usr/share/fish/vendor_completions.d/task.fish
check      : |
    # Fix a couple of tests that are broken because we're overriding the version
    sed -i "s|TASK_VERSION=unknown|TASK_VERSION=v$version|g" task_test.go
    go test ./...
