name       : go-task
version    : 3.29.1
release    : 5
homepage   : https://taskfile.dev/
source     :
    - https://github.com/go-task/task/archive/refs/tags/v3.29.1.tar.gz : 689cd24f2e6af6459bed95f634ab8b50a2344a4f097e69ff1df7027bbc493cfa
license    : MIT
component  : programming.tools
networking : yes
summary    : A task runner / simpler Make alternative written in Go
description: |
    A task runner / simpler Make alternative written in Go 
clang      : yes
builddeps  :
    - golang
environment: |
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
    # Make sure the version ends up in the binary. go-releaser typically handles this but we're not using that
    sed -i "s|version = \"\"|version = \"v$version\"|g" internal/version/version.go

    # Unfortunately /usr/bin/task is already taken so we have to convert everything to go-task instead
    sed -i 's/complete -F _task task/complete -F _task go-task/' completion/bash/task.bash
    sed -i 's/set GO_TASK_PROGNAME task/set GO_TASK_PROGNAME go-task/' completion/fish/task.fish
    sed -i 's/#compdef task/#compdef go-task/' completion/zsh/_task
    sed -i 's/cmd=(task)/cmd=(go-task)/' completion/zsh/_task
build      : |
    go build -v -o bin ./cmd/task
install    : |
    install -Dm00755 bin/task $installdir/usr/bin/go-task

    # Completions
    install -Dm00644 completion/bash/task.bash $installdir/usr/share/bash-completion/completions/go-task
    install -Dm00644 completion/zsh/_task $installdir/usr/share/zsh/site-functions/_go-task
    install -Dm00644 completion/fish/task.fish $installdir/usr/share/fish/vendor_completions.d/go-task.fish
check      : |
    # Fix a couple of tests that are broken because we're overriding the version
    sed -i "s|TASK_VERSION=unknown|TASK_VERSION=v$version|g" task_test.go
    go test ./...
